### ISSUE TITLE
Does not return if the command is not executable by user's primary group

### ISSUE THREAD

**Issue by whs** [isaacs/node-which#4]
Steps to reproduce:

1. `sudo chmod o-x /usr/bin/make`
2. `sudo chown root:sudo /usr/bin/make`
3. Run a `node-gyp build` from a user who is a member of group `sudo`, but `sudo` is not his primary group

(Tested on Debian 6.0.8)

node-gyp will complain about missing `make`, even if `make` is in fact executable by current user.

[Related SO](http://stackoverflow.com/questions/20125789/error-not-found-make)

**Comment by isaacs** [comment]
Yes, we need to check against all the results from `process.getgroups()` if the function is available.  Patch welcome.
